export const blogPosts = [
  {
    slug: "onde-ficar-na-chapada-dos-veadeiros",
    title: "Onde ficar na Chapada dos Veadeiros",
    subtitle: "Alto Paraíso, São Jorge ou Cavalcante? Entenda as diferenças.",
    category: "Hospedagem",
    date: "Maio 2026",
    content: "Escolher a base certa é fundamental...",
  },
  {
    slug: "alto-paraiso-ou-sao-jorge-qual-escolher",
    title: "Alto Paraíso ou São Jorge: qual escolher?",
    subtitle: "Um comparativo detalhado entre as duas principais vilas.",
    category: "Planejamento",
    date: "Abril 2026",
    content: "Cada vila tem sua alma única...",
  },
  {
    slug: "roteiro-de-3-dias-na-chapada-dos-veadeiros",
    title: "Roteiro de 3 dias na Chapada dos Veadeiros",
    subtitle: "O que não pode faltar em um feriado curto.",
    category: "Roteiros",
    date: "Maio 2026",
    content: "Três dias intensos de natureza...",
  },
  {
    slug: "roteiro-de-5-dias-na-chapada-dos-veadeiros",
    title: "Roteiro de 5 dias na Chapada dos Veadeiros",
    subtitle: "A jornada ideal para viver o destino com calma.",
    category: "Roteiros",
    date: "Maio 2026",
    content: "Explore o melhor do cerrado...",
  },
  {
    slug: "melhores-cachoeiras-da-chapada-dos-veadeiros",
    title: "Melhores cachoeiras da Chapada dos Veadeiros",
    subtitle: "Nossa seleção das quedas imperdíveis.",
    category: "Turismo",
    date: "Abril 2026",
    content: "De Santa Bárbara ao Segredo...",
  },
  {
    slug: "pousadas-romanticas-na-chapada",
    title: "Pousadas românticas na Chapada",
    subtitle: "Hospedagens para casais que buscam charme e silêncio.",
    category: "Curadoria",
    date: "Maio 2026",
    content: "Momentos especiais no cerrado...",
  },
  {
    slug: "pousadas-em-alto-paraiso",
    title: "Pousadas em Alto Paraíso",
    subtitle: "As melhores opções na cidade mística.",
    category: "Hospedagem",
    date: "Abril 2026",
    content: "Variedade e estrutura...",
  },
  {
    slug: "pousadas-em-sao-jorge",
    title: "Pousadas em São Jorge",
    subtitle: "Onde ficar na vila mais charmosa da região.",
    category: "Hospedagem",
    date: "Abril 2026",
    content: "Rústico e sofisticado...",
  },
  {
    slug: "cavalcante-e-santa-barbara",
    title: "Cavalcante e Santa Bárbara",
    subtitle: "Tudo o que você precisa saber para visitar a joia da Chapada.",
    category: "Turismo",
    date: "Maio 2026",
    content: "Cultura Kalunga e águas azuis...",
  },
  {
    slug: "quando-ir-para-a-chapada",
    title: "Quando ir para a Chapada",
    subtitle: "Seca ou chuva? Entenda as estações do cerrado.",
    category: "Planejamento",
    date: "Março 2026",
    content: "Cada época tem seu encanto...",
  },
  {
    slug: "como-chegar-na-chapada",
    title: "Como chegar na Chapada",
    subtitle: "Estradas, voos e as melhores rotas saindo de Brasília.",
    category: "Planejamento",
    date: "Março 2026",
    content: "O caminho para o paraíso...",
  },
  {
    slug: "guia-para-primeira-viagem-a-chapada",
    title: "Guia para primeira viagem à Chapada",
    subtitle: "Evite erros comuns e planeje a viagem perfeita.",
    category: "Planejamento",
    date: "Maio 2026",
    content: "Seu primeiro passo no Planalto Central...",
  }
];
